export const AdventureWork = [
  {
    id: 1,
    title: "ROSF Business Clinic Impact Documentary",
    client: "Rose of Sharon Foundation (ROSF)",
    industry: "Non-Profit / Women Empowerment / Social Impact",
    serviceProvided:
      "Documentary Production, Storytelling Strategy, Nationwide Content Capture, Impact Showcasing",
    objective:
      "Document and showcase the impact of ROSF’s Business Clinic initiative, highlight attendees and winners, increase visibility of beneficiary businesses, strengthen credibility, and create a long-term storytelling asset.",
    strategy: [
      "Traveled across multiple states to film participating businesses.",
      "Conducted in-depth interviews with beneficiaries and winners.",
      "Captured authentic business operations, growth stories, and transformation journeys.",
      "Structured the documentary to emphasize empowerment, sustainability, and measurable progress.",
      "Delivered a compelling visual narrative that elevated the Foundation’s work beyond event documentation.",
    ],
    results: [
      "Increased visibility for showcased businesses.",
      "Improved credibility and positioning for ROSF.",
      "Strengthened trust among stakeholders and partners.",
      "Provided beneficiaries with high-quality promotional content that contributed to business growth.",
      "Created a long-term brand asset for ROSF’s fundraising and impact reporting.",
    ],
    images: [],
    videoUrl: ["https://youtu.be/MCqYpD-GQeI?si=PAVggxFOxjKZCtei"],
    documents: [],
    category: "Documentary / Storytelling",
    tags: ["Documentary", "Impact", "Social Change"],
    slug: "rosf-business-clinic",
  },
  {
    id: 2,
    title: "Ogun State GRA Regeneration Scheme",
    client: "Ogun State Ministry of Housing (OGSGRAHomes)",
    industry: "Public Sector / Urban Development / Real Estate Development",
    serviceProvided:
      "Strategic Communications, Campaign Strategy, Content Development, Brochure Design & Production, Influencer Positioning Strategy",
    objective:
      "Communicate the vision and value of the GRA regeneration and housing scheme, increase public confidence, attract investors, strengthen credibility, and position OGSGRAHomes as a premium urban initiative.",
    strategy: [
      "Developed a strategic messaging framework simplifying complex urban development info.",
      "Designed and produced high-quality investor-focused brochure.",
      "Created structured content assets and storytelling angles for public engagement.",
      "Proposed influencer and credibility strategy leveraging respected cultural and national figures.",
      "Balanced technical info with aspirational positioning for effective perception management.",
    ],
    results: [
      "Elevated perception of the regeneration scheme as structured and premium.",
      "Stronger investor confidence through professionally designed materials.",
      "Enhanced cultural and institutional credibility through influencer strategy.",
      "Clearer public understanding of the project’s long-term value.",
    ],
    images: [],
    videoUrl: [],
    documents: [],
    category: "Strategic Communications / Urban Development",
    tags: ["Campaign", "Strategy", "Influencer"],
    slug: "ogra-regeneration-scheme",
  },
  {
    id: 3,
    title: "Lagos International Trade Fair Experience",
    client: "Leadway Group",
    industry: "Financial Services",
    serviceProvided:
      "Experiential Marketing, Exhibition Design & Execution, Brand Activation, Event Strategy",
    objective:
      "Increase brand visibility at Lagos International Trade Fair, drive foot traffic, generate leads, and reinforce Leadway’s trusted insurance brand positioning.",
    strategy: [
      "Designed an engaging and visually compelling pavilion experience.",
      "Structured interactive engagement touchpoints to attract attendees.",
      "Coordinated on-ground brand ambassadors and engagement scripts.",
      "Integrated digital amplification to extend reach beyond the venue.",
    ],
    results: [
      "Strong foot traffic and audience engagement.",
      "Increased brand recall during the fair.",
      "Qualified lead generation.",
      "Strengthened brand positioning in the competitive insurance landscape.",
    ],
    images: [
      "/case-studies/leadway-tradefair/image1.png",
      "/case-studies/leadway-tradefair/image2.png",
      "/case-studies/leadway-tradefair/image3.png",
      "/case-studies/leadway-tradefair/image4.png",
      "/case-studies/leadway-tradefair/image5.png",
      "/case-studies/leadway-tradefair/image6.png",
    ],
    videoUrl: [
      "https://drive.google.com/file/d/1H3K0YQoZTTyCG2pt_mlePNoxaYpOA3lb/view?resourcekey",
    ],
    documents: [
      {
        id: 1,
        name: "Leadway-Tradefair Exhibition Report",
        url: "https://docs.google.com/presentation/d/1B6Nqus5QDKKgSC5pcr1jb4vPid4HSZqU/edit?slide=id.g3a02b1eee09_0_89#slide=id.g3a02b1eee09_0_89",
        type: "presentation",
      },
    ],
    category: "Experiential Marketing / Brand Activation",
    tags: ["Event", "Engagement", "Activation"],
    slug: "lagos-international-trade-fair",
  },
  {
    id: 4,
    title: "Creative Block – Youth Culture & Experiential Strategy",
    client: "Leadway Group",
    industry: "Financial Services",
    serviceProvided:
      "Strategic Concept Development, Experiential Marketing, Creative Direction, Event Execution, Audience Engagement Design",
    objective:
      "Position Leadway as youth-aligned and forward-thinking, increase brand relevance among younger demographics, drive foot traffic and engagement, and convert interaction into business outcomes.",
    strategy: [
      "Developed strategic direction integrating culture, creativity, and interactive brand experience.",
      "Designed an innovative interactive game to capture audience attention.",
      "Structured engagement touchpoints blending fun with subtle brand education.",
      "Coordinated on-ground activation for visibility and crowd retention.",
      "Ensured brand messaging aligned with youth-focused atmosphere.",
    ],
    results: [
      "High youth turnout and heavy foot traffic at activation stand.",
      "Strong engagement levels driven by interactive game.",
      "Increased brand affinity among younger audiences.",
      "Leadway sealed one of its biggest deals directly from the event.",
      "Elevated perception as innovative, culture-driven, and youth-friendly.",
    ],
    images: [
      "/case-studies/leadway-creativeblock/image1.jpg",
      "/case-studies/leadway-creativeblock/image2.jpg",
      "/case-studies/leadway-creativeblock/image3.jpg",
      "/case-studies/leadway-creativeblock/image4.jpg",
    ],
    videoUrl: [],
    documents: [],
    category: "Experiential Marketing / Youth Engagement",
    tags: ["Youth", "Culture", "Interactive"],
    slug: "creative-block-youth-strategy",
  },
  {
    id: 5,
    title: "NFWP Stakeholder Engagement & Public Awareness Campaign",
    client: "Nigeria For Women Project (NFWP) – A World Bank Initiative",
    industry: "International Development / Public Sector / Social Impact",
    serviceProvided:
      "Strategic Communications, Stakeholder Engagement, Public Awareness Campaign, Experiential Activation Support, Media Visibility",
    objective:
      "Increase awareness of NFWP initiative, drive stakeholder engagement, communicate impact clearly, position as credible and transformative, and strengthen public understanding and participation.",
    strategy: [
      "Developed communications framework translating technical goals into clear public messaging.",
      "Structured stakeholder engagement touchpoints for collaboration.",
      "Supported event execution and media visibility to amplify awareness.",
      "Created content assets aligned with World Bank standards of clarity, transparency, and accountability.",
      "Ensured consistent message delivery across platforms and audiences.",
    ],
    results: [
      "Increased visibility and awareness of NFWP initiative.",
      "Stronger stakeholder engagement and alignment.",
      "Improved public understanding of objectives and impact.",
      "Reinforced initiative’s credibility within development ecosystem.",
      "Enhanced positioning as a transformative workforce intervention.",
    ],
    images: [],
    videoUrl: [],
    documents: [],
    category: "Strategic Communications / Public Awareness",
    tags: ["Engagement", "Stakeholders", "Impact"],
    slug: "nfwp-stakeholder-campaign",
  },
  {
    id: 6,
    title: "inDrive Campus Market Penetration Campaign",
    client: "inDrive",
    industry: "Mobility / Ride-Hailing / Technology",
    serviceProvided:
      "BTL Activation, Campus Marketing Strategy, Ambassador Program Development, Influencer Engagement, User Acquisition Campaign",
    objective:
      "Drive app downloads, increase active usage among students, penetrate key university markets, build brand affinity within youth communities, and create sustainable campus-driven growth channels.",
    strategy: [
      "Developed BTL campus activation strategy focused on University of Ibadan, University of Benin, and Rivers State University.",
      "Launched structured Campus Ambassador Program and recruited influential student advocates.",
      "Executed on-ground campus activations and engagement drives.",
      "Created direct app download funnels during engagements.",
      "Educated students on inDrive’s unique pricing and negotiation model.",
    ],
    results: [
      "Significant increase in app downloads across targeted campuses.",
      "Measurable growth in app usage and ride frequency among students.",
      "Strong brand visibility within target universities.",
      "Established a repeatable campus ambassador growth model.",
      "Strengthened inDrive’s youth market penetration in Nigeria.",
    ],
    images: [],
    videoUrl: [
      "https://docs.google.com/videos/d/1IrmrHlFsS0jdlVCmgX1puFJhDSm6c6Es5Dwx9oN4iQQ/edit?usp=sharing",
      "https://docs.google.com/videos/d/1GJUP72VFKRKv7ngPgGDHYS86Ry5IpiWoM_N8gpiSAK8/edit?usp=sharing",
      "https://docs.google.com/videos/d/12DmkBHCZwfvYUFaK-hA87eptPs6WXqRQ8-3JDrLaIco/edit?usp=sharing",
    ],
    documents: [],
    category: "Campus Marketing / BTL Activation",
    tags: ["Youth", "Activation", "App Downloads"],
    slug: "indrive-campus-campaign",
  },
];
